version: '3.9'
services:
  db:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: mysql-db
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3310:3306"
