version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: my_test_db
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
