version: '3.9'
services:
  db:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3310:3306"
  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: postgresdb
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  pgadmin-data:
