version: '3.1'
services:
    mongo:
        container_name: mongodb-testing
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
        volumes:
            - /data/db:/data/db
